name: dependency

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: List dependencies
        run: go list -json -m all > go.list

      - name: Run nancy
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2
