name: lint

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest
          args: --timeout 5m
