name: lint

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Telegram
        env:
          TELEGRAM_ACCESS_TOKEN: ${{ secrets.TELEGRAM_ACCESS_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          go run ./cmd/telegram -text=user ${{ github.event.pull_request.user.login }} make PR

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 5m
          skip-go-installation: true
